export default function VentureAutopilotDecisionsPage() {
  return (
    <main>
      <h1>Lifecycle Decisions</h1>
      <p>Review scale, hold, pivot, and shutdown decisions generated by the venture autopilot.</p>
    </main>
  );
}
